### ISSUE TITLE
Relax requirements when some attributes are malformed

### ISSUE THREAD

**Issue by andersy005** [xarray-contrib/cf-xarray#216]
I have a dataset with a malformed `cell_measures` attribute. This malformed attribute causes `cf_xarray` to completely fail. I expected `cf_xarray` to be **less strict** when it comes to missing or malformed attributes. I was wondering whether warning the user instead of raising an exception would be a reasonable thing to support? I am asking because I think it'd be nice to use `cf_xarray` to discover other CF metadata even when a few attributes are malformed.

<details><summary>Example</summary>

```python
In [1]: import xarray as xr

In [2]: import cf_xarray

In [3]: ds = xr.tutorial.open_dataset('air_temperature')

In [4]: ds.cf
Out[4]: 
Coordinates:
- CF Axes: * X: ['lon']
           * Y: ['lat']
           * T: ['time']
             Z: n/a

- CF Coordinates: * longitude: ['lon']
                  * latitude: ['lat']
                  * time: ['time']
                    vertical: n/a

- Cell Measures:   area, volume: n/a

- Standard Names: * latitude: ['lat']
                  * longitude: ['lon']
                  * time: ['time']

Data Variables:
- Cell Measures:   area, volume: n/a

- Standard Names:   n/a

In [5]: ds
Out[5]: 
<xarray.Dataset>
Dimensions:  (lat: 25, lon: 53, time: 2920)
Coordinates:
  * lat      (lat) float32 75.0 72.5 70.0 67.5 65.0 ... 25.0 22.5 20.0 17.5 15.0
  * lon      (lon) float32 200.0 202.5 205.0 207.5 ... 322.5 325.0 327.5 330.0
  * time     (time) datetime64[ns] 2013-01-01 ... 2014-12-31T18:00:00
Data variables:
    air      (time, lat, lon) float32 ...
Attributes:
    Conventions:  COARDS
    title:        4x daily NMC reanalysis (1948)
    description:  Data is from NMC initialized reanalysis\n(4x/day).  These a...
    platform:     Model
    references:   http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanaly...
```

Introducing the malformed attribute breaks the accessor: 

```python
In [6]: ds.air.attrs['cell_measures'] = '--OPT'

In [7]: ds.cf
Out[7]: ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/cf_xarray/accessor.py in __repr__(self)
   1086 
   1087         text = "Coordinates:"
-> 1088         text += make_text_section("CF Axes", self.axes, coords, _AXIS_NAMES)
   1089         text += make_text_section(
   1090             "CF Coordinates", self.coordinates, coords, _COORD_NAMES

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/cf_xarray/accessor.py in axes(self)
   1146         Will be ("X", "Y", "Z", "T") or a subset thereof.
   1147         """
-> 1148         vardict = {key: _get_coords(self._obj, key) for key in _AXIS_NAMES}
   1149 
   1150         return {k: sorted(v) for k, v in vardict.items() if v}

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/cf_xarray/accessor.py in <dictcomp>(.0)
   1146         Will be ("X", "Y", "Z", "T") or a subset thereof.
   1147         """
-> 1148         vardict = {key: _get_coords(self._obj, key) for key in _AXIS_NAMES}
   1149 
   1150         return {k: sorted(v) for k, v in vardict.items() if v}

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/cf_xarray/accessor.py in _get_coords(obj, key)
    392     'area', 'volume'), or arbitrary measures, or standard names present in .coords
    393     """
--> 394     return [k for k in _get_all(obj, key) if k in obj.coords]
    395 
    396 

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/cf_xarray/accessor.py in _get_all(obj, key)
    367     """
    368     all_mappers = (_get_axis_coord, _get_measure, _get_with_standard_name)
--> 369     results = apply_mapper(all_mappers, obj, key, error=False, default=None)
    370     return results
    371 

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/cf_xarray/accessor.py in apply_mapper(mappers, obj, key, error, default)
    188     results = []
    189     for mapper in mappers:
--> 190         results.append(_apply_single_mapper(mapper))
    191 
    192     flat = list(itertools.chain(*results))

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/cf_xarray/accessor.py in _apply_single_mapper(mapper)
    172 
    173         try:
--> 174             results = mapper(obj, key)
    175         except KeyError as e:
    176             if error or "I expected only one." in repr(e):

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/cf_xarray/accessor.py in _get_measure(obj, key)
    334         if "cell_measures" in da.attrs:
    335             attr = da.attrs["cell_measures"]
--> 336             measures = parse_cell_methods_attr(attr)
    337             if key in measures:
    338                 results.update([measures[key]])

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/cf_xarray/utils.py in parse_cell_methods_attr(attr)
     39     strings = [s for scolons in attr.split(":") for s in scolons.split()]
     40     if len(strings) % 2 != 0:
---> 41         raise ValueError(f"attrs['cell_measures'] = {attr!r} is malformed.")
     42 
     43     return dict(zip(strings[slice(0, None, 2)], strings[slice(1, None, 2)]))

ValueError: attrs['cell_measures'] = '--OPT' is malformed.

```

</details>

**Comment by dcherian** [comment]
This weird CMOR thing is fixed on main. Do you know what `--OPT` means?

**Comment by andersy005** [comment]
> Do you know what --OPT means?

I have no idea. I just found it in a CMIP6 data file

> This weird CMOR thing is fixed on main. 

Unless I'm missing something, I am still the same error with the main branch: 


```python
In [1]: import cf_xarray

In [2]: cf_xarray.__version__
Out[2]: '0.5.2.dev13+g64e8695'

In [3]: import xarray as xr

In [4]: file = '/glade/collections/cmip/CMIP6/CMIP/AWI/AWI-CM-1-1-MR/abrupt-4xCO2/r1i1p1f1/Omon/tauuo/
   ...: gn/v20181218/tauuo/tauuo_Omon_AWI-CM-1-1-MR_abrupt-4xCO2_r1i1p1f1_gn_198101-199012.nc'

In [5]: ds = xr.open_dataset(file, chunks={})

In [6]: ds.cf
Out[6]: ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/glade/work/abanihi/opt/miniconda/envs/playground/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

/glade/work/abanihi/devel/xarray-contrib/cf-xarray/cf_xarray/accessor.py in __repr__(self)
   1020 
   1021         text = "Coordinates:"
-> 1022         text += make_text_section("CF Axes", self.axes, coords, _AXIS_NAMES)
   1023         text += make_text_section(
   1024             "CF Coordinates", self.coordinates, coords, _COORD_NAMES

/glade/work/abanihi/devel/xarray-contrib/cf-xarray/cf_xarray/accessor.py in axes(self)
   1080         Will be ("X", "Y", "Z", "T") or a subset thereof.
   1081         """
-> 1082         vardict = {key: _get_coords(self._obj, key) for key in _AXIS_NAMES}
   1083 
   1084         return {k: sorted(v) for k, v in vardict.items() if v}

/glade/work/abanihi/devel/xarray-contrib/cf-xarray/cf_xarray/accessor.py in <dictcomp>(.0)
   1080         Will be ("X", "Y", "Z", "T") or a subset thereof.
   1081         """
-> 1082         vardict = {key: _get_coords(self._obj, key) for key in _AXIS_NAMES}
   1083 
   1084         return {k: sorted(v) for k, v in vardict.items() if v}

/glade/work/abanihi/devel/xarray-contrib/cf-xarray/cf_xarray/accessor.py in _get_coords(obj, key)
    305     'area', 'volume'), or arbitrary measures, or standard names present in .coords
    306     """
--> 307     return [k for k in _get_all(obj, key) if k in obj.coords]
    308 
    309 

/glade/work/abanihi/devel/xarray-contrib/cf-xarray/cf_xarray/accessor.py in _get_all(obj, key)
    280     """
    281     all_mappers = (_get_axis_coord, _get_measure, _get_with_standard_name)
--> 282     results = apply_mapper(all_mappers, obj, key, error=False, default=None)
    283     return results
    284 

/glade/work/abanihi/devel/xarray-contrib/cf-xarray/cf_xarray/accessor.py in apply_mapper(mappers, obj, key, error, default)
    101     results = []
    102     for mapper in mappers:
--> 103         results.append(_apply_single_mapper(mapper))
    104 
    105     flat = list(itertools.chain(*results))

/glade/work/abanihi/devel/xarray-contrib/cf-xarray/cf_xarray/accessor.py in _apply_single_mapper(mapper)
     85 
     86         try:
---> 87             results = mapper(obj, key)
     88         except KeyError as e:
     89             if error or "I expected only one." in repr(e):

/glade/work/abanihi/devel/xarray-contrib/cf-xarray/cf_xarray/accessor.py in _get_measure(obj, key)
    247         if "cell_measures" in da.attrs:
    248             attr = da.attrs["cell_measures"]
--> 249             measures = parse_cell_methods_attr(attr)
    250             if key in measures:
    251                 results.update([measures[key]])

/glade/work/abanihi/devel/xarray-contrib/cf-xarray/cf_xarray/utils.py in parse_cell_methods_attr(attr)
     39     strings = [s for scolons in attr.split(":") for s in scolons.split()]
     40     if len(strings) % 2 != 0:
---> 41         raise ValueError(f"attrs['cell_measures'] = {attr!r} is malformed.")
     42 
     43     return dict(zip(strings[slice(0, None, 2)], strings[slice(1, None, 2)]))

ValueError: attrs['cell_measures'] = '--OPT' is malformed.
```

**Comment by andersy005** [comment]
As I understand it, https://github.com/xarray-contrib/cf-xarray/pull/196 addressed the issue partially. The call to `parse_cell_methods_attr()` should be in a `try except` block, right? 

https://github.com/xarray-contrib/cf-xarray/blob/64e86954c46642df6f11323d1442fbc70c8fd1bb/cf_xarray/accessor.py#L245-L249

**Comment by malmans2** [comment]
We need a `try except` here as well:
https://github.com/xarray-contrib/cf-xarray/blob/64e86954c46642df6f11323d1442fbc70c8fd1bb/cf_xarray/accessor.py#L1129-L1130

Maybe it's easier to add an argument `error: bool` in `parse_cell_methods_attr` and warn+return an empty dict when `error is False`.

**Comment by malmans2** [comment]
Found this about OPT: https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/40

Here is an explanation of `--OPT` and `--MODEL` for `cell_measures`: http://clipc-services.ceda.ac.uk/dreq/u/ATTRIBUTE::structure.cell_measures.html

**Comment by dcherian** [comment]
nice find. thanks!
